name: Kralbet M3U Oluşturucu

on:
  schedule:
    - cron: '0 */6 * * *'  # Her 6 saatte bir çalışır
  workflow_dispatch:       # Manuel çalıştırmaya izin verir

jobs:
  m3u-olustur:
    runs-on: ubuntu-latest
    
    steps:
    - name: Kodları al
      uses: actions/checkout@v4
      
    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Gerekli paketleri yükle
      run: |
        pip install requests beautifulsoup4
        
    - name: M3U oluşturucuyu çalıştır
      run: python Pythonlar/kralbet.py
      
    -   name: Değişiklikleri Git'e Commit Et ve Push'la
    
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add kralbet.m3u
          git commit -m "🔄 Otomatik m3u güncelleme" || echo "No changes to commit"
          git push



