name: Generate kralbet.m3u

on:
  schedule:
    - cron: '*/30 * * * *'  # Her 30 dakikada bir
  workflow_dispatch:

jobs:
  generate-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v4

      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Gereksinimleri yükle
        run: pip install requests

      - name: kralbet.m3u dosyasını oluştur
        run: python Pythonlar/kralbet.py

      - name: Değişiklikleri push'la
        continue-on-error: true
        run: |
         git config user.name "GitHub Actions"
         git config user.email "actions@github.com"
         git add kralbet.m3u
         git commit -m "Güncel kralbet.m3u" || echo "Commit edilecek değişiklik yok"
         git push
