name: M3U Güncelleme Botu

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # Her gün saat 03:00'te çalışır (UTC)

jobs:
  guncelle:
    runs-on: ubuntu-latest

    steps:
      - name: Reposu klonla
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Bağımlılıkları yükle
        run: pip install pyyaml

      - name: Scripti çalıştır
        run: python Pythonlar/vetteltv.py

      - name: Değişiklikleri commit et
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add vetteltv.m3u
          git commit -m "Otomatik M3U güncellemesi"
          git push
